### ISSUE TITLE
Partner ID set up

### ISSUE THREAD

**Issue by liquidoxygen96** [yearn/macarena-finance#12]
### Scope

First and foremost, thank you for the opensource efforts by Yearn. The aim of this project is to learn a bit more about Decentralized Finance and to further the scope of decentralizing the UserInterface to the Yearn platform. Hope to learn more and find success in the space

### Plan

1. Set up working UI for interacting with Yearn 
2. Marketing the website portal to get a sense for engagement and interest in DeFi from my end
3. gauge interest in people willing to work on furthering the project in our own unique way 

### People

This is a sole effort by the submitter of this request. Hoping to onboard more members to this solo team. This is a learning effort, for now. 

### partnerID

0xE3F751a1712EfFaB7a960321B08366e36d8a6Ccc

### Condition

- [X] I agree

**Comment by saltyfacu** [comment]
Hey, that's great! Is the website live already? Anything you want to ask?

Cheers

**Comment by karelianpie** [comment]
@saltyfacu is this still relevant or can it be closed?

**Comment by karelianpie** [comment]
Closing as no updates
