### ISSUE TITLE
coquillage.eth

### ISSUE THREAD

**Issue by Bild96** [yearn/macarena-finance#17]
### Scope

Participant in online [ETHonline](https://online.ethglobal.com/) 2022 Hackathon. 

### Plan

imporoving UI, and deploying in IPFS 

### People

[github.com/bild96](https://github.com/Bild96/coquillage.eth)

### partnerID

0xfd7a470001364d707c81074142b6aC9248B0b0cc

### Condition

- [X] I agree

**Comment by karelianpie** [comment]
@saltyfacu is this still relevant or can it be closed?
