### ISSUE TITLE
Bug: Unhandled type errors when re-connecting wallets

### ISSUE THREAD

**Issue by SeanGrindal** [yearn/macarena-finance#22]
### What happened 
Connected and disconnecting a wallet throughs type errors which are not handled. 

![image](https://user-images.githubusercontent.com/44325789/233893911-f9d14736-3289-465d-b581-089e735a597f.png)

### To Reproduce
Connect, disconnect, and reconnect a wallet.

**Comment by karelianpie** [comment]
Hey @SeanGrindal, thank you for the bug report!

Are you still able to see the MetaMask error and the Uncaught in promise? I've tried to repro (after upgrading to the latest web-lib) and they seem to not happen anymore.

The type error, failed to fetch can be safely ignored as it's not critical for now. That's just the PWA setup.

**Comment by karelianpie** [comment]
Closing as no updates, @SeanGrindal feel free to open again if the issue remains.
